### ISSUE TITLE
For Debian Bullseye ?

### ISSUE THREAD

**Issue by ogmkp** [runner365/srt_encoder#4]
Hello.

Debian 11 Bullseye comes with ffmpeg version 4.3.2 in its stable release, is it possible to integrate?

Another question: it is possible to use vaapi ?

Thanks !

**Comment by kevev** [comment]
I tried creating a patch using a diff from ffmpeg.c and could not get very far. Hoping for an update of this project for the latest ffmpeg source.

**Comment by runner365** [comment]
> I tried creating a patch using a diff from ffmpeg.c and could not get very far. Hoping for an update of this project for the latest ffmpeg source.

Ok, I will do it in this month. It will be for ffmpeg5.1.

**Comment by kevev** [comment]
> > I tried creating a patch using a diff from ffmpeg.c and could not get very far. Hoping for an update of this project for the latest ffmpeg source.
> 
> Ok, I will do it in this month. It will be for ffmpeg5.1.

Thank You very much!!

**Comment by runner365** [comment]
> > > I tried creating a patch using a diff from ffmpeg.c and could not get very far. Hoping for an update of this project for the latest ffmpeg source.
> > 
> > 
> > Ok, I will do it in this month. It will be for ffmpeg5.1.
> 
> Thank You very much!!

I added the ffmpeg5.1 which is from git(https://git.ffmpeg.org/ffmpeg.git).

**Comment by kevev** [comment]
Getting error:

objpool.h: No such file or directory

Fixed with: apt-get install fcitx-libs-dev

**Comment by kevev** [comment]
FFMPEG does not seem to build properly. Tried 4.1 from your wiki, 4.4.3 and 5.1.2 .

4.1 error:

libavformat/libsrt.c:337:50: error: ‘SRTO_SMOOTHER’ undeclared (first use in this function); did you mean ‘SRTO_SENDER’?
  337 |         (s->smoother && libsrt_setsockopt(h, fd, SRTO_SMOOTHER, "SRTO_SMOOTHER", s->smoother, strlen(s->smoother)) < 0) ||
      |                                                  ^~~~~~~~~~~~~
      |                                                  SRTO_SENDER
libavformat/libsrt.c:337:50: note: each undeclared identifier is reported only once for each function it appears in
libavformat/libsrt.c: In function ‘libsrt_setup’:
libavformat/libsrt.c:401:5: warning: ‘srt_socket’ is deprecated [-Wdeprecated-declarations]
  401 |     fd = srt_socket(cur_ai->ai_family, cur_ai->ai_socktype, 0);
      |     ^~
In file included from libavformat/libsrt.c:24:
/usr/local/include/srt/srt.h:756:41: note: declared here
  756 | SRT_ATR_DEPRECATED_PX SRT_API SRTSOCKET srt_socket(int, int, int) SRT_ATR_DEPRECATED;
      |                                         ^~~~~~~~~~
make: *** [ffbuild/common.mak:60: libavformat/libsrt.o] Error 1

4.4.3 error:

CC      fftools/ffprobe.o
fftools/ffmpeg.c:554:6: error: conflicting types for ‘sub2video_update’; have ‘void(InputStream *, AVSubtitle *)’
  554 | void sub2video_update(InputStream *ist, AVSubtitle *sub)
      |      ^~~~~~~~~~~~~~~~
In file included from fftools/ffmpeg.c:104:
fftools/ffmpeg.h:663:6: note: previous declaration of ‘sub2video_update’ with type ‘void(InputStream *, int64_t,  AVSubtitle *)’ {aka ‘void(InputStream *, long int,  AVSubtitle *)’}
  663 | void sub2video_update(InputStream *ist, int64_t heartbeat_pts, AVSubtitle *sub);
      |      ^~~~~~~~~~~~~~~~
fftools/ffmpeg.c: In function ‘ffmpeg_cleanup’:
fftools/ffmpeg.c:867:28: error: ‘OutputStream’ has no member named ‘nb_bitstream_filters’
  867 |         for (j = 0; j < ost->nb_bitstream_filters; j++)
      |                            ^~
fftools/ffmpeg.c:868:25: warning: passing argument 1 of ‘av_bsf_free’ from incompatible pointer type [-Wincompatible-pointer-types]
  868 |             av_bsf_free(&ost->bsf_ctx[j]);
      |                         ^~~~~~~~~~~~~~~~
      |                         |
      |                         AVBSFContext *
In file included from ./libavcodec/avcodec.h:44,
                 from ./libavformat/avformat.h:312,
                 from fftools/ffmpeg.c:43:
./libavcodec/bsf.h:226:33: note: expected ‘AVBSFContext **’ but argument is of type ‘AVBSFContext *’
  226 | void av_bsf_free(AVBSFContext **ctx);
      |                  ~~~~~~~~~~~~~~~^~~
fftools/ffmpeg.c: In function ‘output_packet’:
fftools/ffmpeg.c:1168:12: error: ‘OutputStream’ has no member named ‘nb_bitstream_filters’
 1168 |     if (ost->nb_bitstream_filters) {
      |            ^~
fftools/ffmpeg.c:1171:46: error: incompatible type for argument 1 of ‘av_bsf_send_packet’
 1171 |         ret = av_bsf_send_packet(ost->bsf_ctx[0], eof ? NULL : pkt);
      |                                  ~~~~~~~~~~~~^~~
      |                                              |
      |                                              AVBSFContext
./libavcodec/bsf.h:189:38: note: expected ‘AVBSFContext *’ but argument is of type ‘AVBSFContext’
  189 | int av_bsf_send_packet(AVBSFContext *ctx, AVPacket *pkt);
      |                        ~~~~~~~~~~~~~~^~~
fftools/ffmpeg.c:1179:53: error: incompatible type for argument 1 of ‘av_bsf_receive_packet’
 1179 |             ret = av_bsf_receive_packet(ost->bsf_ctx[idx - 1], pkt);
      |                                         ~~~~~~~~~~~~^~~~~~~~~
      |                                                     |
      |                                                     AVBSFContext
./libavcodec/bsf.h:215:41: note: expected ‘AVBSFContext *’ but argument is of type ‘AVBSFContext’
  215 | int av_bsf_receive_packet(AVBSFContext *ctx, AVPacket *pkt);
      |                           ~~~~~~~~~~~~~~^~~
fftools/ffmpeg.c:1190:26: error: ‘OutputStream’ has no member named ‘nb_bitstream_filters’
 1190 |             if (idx < ost->nb_bitstream_filters) {
      |                          ^~
fftools/ffmpeg.c:1191:54: error: incompatible type for argument 1 of ‘av_bsf_send_packet’
 1191 |                 ret = av_bsf_send_packet(ost->bsf_ctx[idx], eof ? NULL : pkt);
      |                                          ~~~~~~~~~~~~^~~~~
      |                                                      |
      |                                                      AVBSFContext
./libavcodec/bsf.h:189:38: note: expected ‘AVBSFContext *’ but argument is of type ‘AVBSFContext’
  189 | int av_bsf_send_packet(AVBSFContext *ctx, AVPacket *pkt);
      |                        ~~~~~~~~~~~~~~^~~
fftools/ffmpeg.c: In function ‘do_audio_out’:
fftools/ffmpeg.c:1233:5: warning: ‘av_init_packet’ is deprecated [-Wdeprecated-declarations]
 1233 |     av_init_packet(&pkt);
      |     ^~~~~~~~~~~~~~
In file included from ./libavcodec/bsf.h:30:
./libavcodec/packet.h:488:6: note: declared here
  488 | void av_init_packet(AVPacket *pkt);
      |      ^~~~~~~~~~~~~~
fftools/ffmpeg.c: In function ‘do_subtitle_out’:
fftools/ffmpeg.c:1351:9: warning: ‘av_init_packet’ is deprecated [-Wdeprecated-declarations]
 1351 |         av_init_packet(&pkt);
      |         ^~~~~~~~~~~~~~
./libavcodec/packet.h:488:6: note: declared here
  488 | void av_init_packet(AVPacket *pkt);
      |      ^~~~~~~~~~~~~~
fftools/ffmpeg.c: In function ‘do_video_out’:
fftools/ffmpeg.c:1515:5: warning: ‘av_init_packet’ is deprecated [-Wdeprecated-declarations]
 1515 |     av_init_packet(&pkt);
      |     ^~~~~~~~~~~~~~
./libavcodec/packet.h:488:6: note: declared here
  488 | void av_init_packet(AVPacket *pkt);
      |      ^~~~~~~~~~~~~~
fftools/ffmpeg.c: In function ‘flush_encoders’:
fftools/ffmpeg.c:2252:17: warning: ‘av_init_packet’ is deprecated [-Wdeprecated-declarations]
 2252 |                 av_init_packet(&pkt);
      |                 ^~~~~~~~~~~~~~
./libavcodec/packet.h:488:6: note: declared here
  488 | void av_init_packet(AVPacket *pkt);
      |      ^~~~~~~~~~~~~~
fftools/ffmpeg.c: In function ‘do_streamcopy’:
fftools/ffmpeg.c:2324:5: warning: ‘av_init_packet’ is deprecated [-Wdeprecated-declarations]
 2324 |     av_init_packet(&opkt);
      |     ^~~~~~~~~~~~~~
./libavcodec/packet.h:488:6: note: declared here
  488 | void av_init_packet(AVPacket *pkt);
      |      ^~~~~~~~~~~~~~
fftools/ffmpeg.c:2398:5: warning: ‘av_copy_packet_side_data’ is deprecated [-Wdeprecated-declarations]
 2398 |     av_copy_packet_side_data(&opkt, pkt);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
./libavcodec/packet.h:559:5: note: declared here
  559 | int av_copy_packet_side_data(AVPacket *dst, const AVPacket *src);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
fftools/ffmpeg.c: In function ‘process_input_packet’:
fftools/ffmpeg.c:2916:9: warning: ‘av_init_packet’ is deprecated [-Wdeprecated-declarations]
 2916 |         av_init_packet(&avpkt);
      |         ^~~~~~~~~~~~~~
./libavcodec/packet.h:488:6: note: declared here
  488 | void av_init_packet(AVPacket *pkt);
      |      ^~~~~~~~~~~~~~
fftools/ffmpeg.c: In function ‘init_input_stream’:
fftools/ffmpeg.c:3221:26: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 3221 |         AVCodec *codec = ist->dec;
      |                          ^~~
fftools/ffmpeg.c:3231:9: warning: ‘thread_safe_callbacks’ is deprecated [-Wdeprecated-declarations]
 3231 |         ist->dec_ctx->thread_safe_callbacks = 1;
      |         ^~~
./libavcodec/avcodec.h:1812:9: note: declared here
 1812 |     int thread_safe_callbacks;
      |         ^~~~~~~~~~~~~~~~~~~~~
fftools/ffmpeg.c: In function ‘init_output_bsfs’:
fftools/ffmpeg.c:3344:13: error: ‘OutputStream’ has no member named ‘nb_bitstream_filters’
 3344 |     if (!ost->nb_bitstream_filters)
      |             ^~
fftools/ffmpeg.c:3347:24: error: ‘OutputStream’ has no member named ‘nb_bitstream_filters’
 3347 |     for (i = 0; i < ost->nb_bitstream_filters; i++) {
      |                        ^~
fftools/ffmpeg.c:3348:15: error: incompatible types when assigning to type ‘AVBSFContext *’ from type ‘AVBSFContext’
 3348 |         ctx = ost->bsf_ctx[i];
      |               ^~~
fftools/ffmpeg.c:3351:62: error: invalid type argument of ‘->’ (have ‘AVBSFContext’)
 3351 |                                       i ? ost->bsf_ctx[i - 1]->par_out : ost->st->codecpar);
      |                                                              ^~
fftools/ffmpeg.c:3355:52: error: invalid type argument of ‘->’ (have ‘AVBSFContext’)
 3355 |         ctx->time_base_in = i ? ost->bsf_ctx[i - 1]->time_base_out : ost->st->time_base;
      |                                                    ^~
fftools/ffmpeg.c:3360:35: error: invalid type argument of ‘->’ (have ‘AVBSFContext’)
 3360 |                    ost->bsf_ctx[i]->filter->name);
      |                                   ^~
fftools/ffmpeg.c:3365:27: error: ‘OutputStream’ has no member named ‘nb_bitstream_filters’
 3365 |     ctx = ost->bsf_ctx[ost->nb_bitstream_filters - 1];
      |                           ^~
fftools/ffmpeg.c: In function ‘init_output_stream’:
fftools/ffmpeg.c:3780:31: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 3780 |         AVCodec      *codec = ost->enc;
      |                               ^~~
fftools/ffmpeg.c:3874:9: warning: ‘avcodec_copy_context’ is deprecated [-Wdeprecated-declarations]
 3874 |         ret = avcodec_copy_context(ost->st->codec, ost->enc_ctx);
      |         ^~~
./libavcodec/avcodec.h:2843:5: note: declared here
 2843 | int avcodec_copy_context(AVCodecContext *dest, const AVCodecContext *src);
      |     ^~~~~~~~~~~~~~~~~~~~
fftools/ffmpeg.c:3874:9: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
 3874 |         ret = avcodec_copy_context(ost->st->codec, ost->enc_ctx);
      |         ^~~
./libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
fftools/ffmpeg.c:3920:9: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
 3920 |         ost->st->codec->codec= ost->enc_ctx->codec;
      |         ^~~
./libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
fftools/ffmpeg.c: In function ‘check_keyboard_interaction’:
fftools/ffmpeg.c:4302:13: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
 4302 |             debug = input_streams[0]->st->codec->debug<<1;
      |             ^~~~~
./libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
fftools/ffmpeg.c:4306:47: error: ‘FF_DEBUG_VIS_QP’ undeclared (first use in this function); did you mean ‘FF_DEBUG_SKIP’?
 4306 |                                              |FF_DEBUG_VIS_QP|FF_DEBUG_VIS_MB_TYPE
      |                                               ^~~~~~~~~~~~~~~
      |                                               FF_DEBUG_SKIP
fftools/ffmpeg.c:4306:47: note: each undeclared identifier is reported only once for each function it appears in
fftools/ffmpeg.c:4306:63: error: ‘FF_DEBUG_VIS_MB_TYPE’ undeclared (first use in this function); did you mean ‘FF_DEBUG_MB_TYPE’?
 4306 |                                              |FF_DEBUG_VIS_QP|FF_DEBUG_VIS_MB_TYPE
      |                                                               ^~~~~~~~~~~~~~~~~~~~
      |                                                               FF_DEBUG_MB_TYPE
fftools/ffmpeg.c:4325:13: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
 4325 |             input_streams[i]->st->codec->debug = debug;
      |             ^~~~~~~~~~~~~
./libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
fftools/ffmpeg.c: In function ‘transcode’:
fftools/ffmpeg.c:5085:22: error: ‘hw_device_ctx’ undeclared (first use in this function)
 5085 |     av_buffer_unref(&hw_device_ctx);
      |                      ^~~~~~~~~~~~~
make: *** [ffbuild/common.mak:67: fftools/ffmpeg.o] Error 1

5.1.2 error:

In file included from fftools/ffmpeg_mux.c:24:
/usr/include/fcitx-utils/objpool.h: In function ‘fcitx_obj_pool_get’:
/usr/include/fcitx-utils/objpool.h:137:28: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
  137 |         return pool->array + fcitx_obj_pool_offset(pool, i) + sizeof(int);
      |                            ^
/usr/include/fcitx-utils/objpool.h:137:61: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
  137 |         return pool->array + fcitx_obj_pool_offset(pool, i) + sizeof(int);
      |                                                             ^
fftools/ffmpeg_mux.c: At top level:
fftools/ffmpeg_mux.c:25:10: fatal error: sync_queue.h: No such file or directory
   25 | #include "sync_queue.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [ffbuild/common.mak:81: fftools/ffmpeg_mux.o] Error 1

******************************************************************************
It seems as though sync_queue.h is no-longer in FFMPEG source.

**Comment by ogmkp** [comment]
I'm closing this old issue, but I'm still following this project.
